version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app # mount for live code reload
    # command: ["gunicorn", "app:app", "-w", "4", "-b", "0.0.0.0:8000"] # for production

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
